# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded JuniperConnect 1.0 [list source [file join $dir juniper_connect.tcl]]
package ifneeded concurrency 1.0 [list source [file join $dir concurrency.tcl]]
package ifneeded countdown 1.0 [list source [file join $dir countdown.tcl]]
package ifneeded delim 1.0 [list source [file join $dir delim.tcl]]
package ifneeded ezhtml 1.0 [list source [file join $dir ezhtml.tcl]]
package ifneeded ezmail 1.0 [list source [file join $dir ezmail.tcl]]
package ifneeded gen 1.1 [list source [file join $dir gen.tcl]]
package ifneeded homeless 1.0 [list source [file join $dir homeless.tcl]]
package ifneeded output 1.1 [list source [file join $dir output.tcl]]
package ifneeded test 1.0 [list source [file join $dir test.tcl]]
package ifneeded textproc 1.0 [list source [file join $dir textproc.tcl]]
