#the script will read yaml templates from this folder
path_templates: ~/juniper-helpers/examples/output_collector/templates

#output files will be deposited in subfolders of this path
output_folder: ~/juniper-helpers/examples/output_collector/output

#router lists... use > for multiline
sample_router_list: >
    r1

sample_router_list_2: >
    10.1.1.1
    10.1.1.2

